version: 0.1
phases:
  install:
    commands:
      - npm ci
      - npm audit
      - npm test
      - npm uninstall *
      - rm -rf ./node_modules
      - npm i --only=prod
      - sed 's/\t//g' < serverless.template > serverless.temp.template
      - aws cloudformation package --template-file serverless.temp.template --s3-bucket ${BUCKET_NAME} --output-template-file transformed-template.json
      - SCORE=`npm run --silent coverage-percentage` &&
        aws sqs send-message --queue-url https://sqs.eu-west-1.amazonaws.com/${ACCOUNT_ID}/env-code-coverage-Queue --message-body "{\"project\":\"evb-local\", \"score\":\"${SCORE}\"}"
artifacts:
  type: zip
  files:
    - transformed-template.json
    - parameters.*.json
